require ('./db/mongoose')
const express = require ('express')
const userRouter = require('./routes/user.routes')
const courseRouter = require('./routes/course.routes')
const cors = require('cors')
require('./db/mongoose')
const app =express()
app.use(cors)
app.use(express.json())
app.use(userRouter)
app.use(courseRouter)
module.exports=app